### ISSUE TITLE
Dynamic Fields with button

### ISSUE THREAD

**Issue by x1mrdonut1x** [rekit/antd-form-builder#33]
Hi, I'm trying to find a way to generate dynamic fields by clicking a button. 

The code below updates the form only after changing the radio value.

[Code Sandbox](https://codesandbox.io/s/relaxed-shadow-zepdk?file=/src/DynamicFields.js)

**Comment by bermann** [comment]
It's because of the way you're updating the state. You should never mutate the old state like in `handleAddField` using push. This is because React will internally compare prev with the new returned value, since you mutate the prev value and pass the same ref, it won't re-render.

In order to get it working you should change the `handleAddField` to:

```
  const handleAddField = () => {
    setMeta(prev => {
      return [...prev, {
        key: "otherFruit",
        label: "Other"
      }];
    });
  };
```

**Comment by x1mrdonut1x** [comment]
Thanks!
